"""
Import ROBINREAL image descriptions from CSV into a local listings.db.

The CSV is generated by generate_robinreal_descriptions.py and contains
listing_id + image_description columns. Run this after a teammate shares
the CSV (or after running the generate script yourself).

Usage:
    uv run python scripts/import_robinreal_descriptions.py
    uv run python scripts/import_robinreal_descriptions.py --csv data/robinreal_image_descriptions.csv --db data/listings.db
    uv run python scripts/import_robinreal_descriptions.py --skip-existing
"""
from __future__ import annotations

import argparse
import csv
import sqlite3
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CSV = ROOT / "data" / "robinreal_image_descriptions.csv"
DEFAULT_DB = ROOT / "data" / "listings.db"


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Import ROBINREAL image descriptions into listings.db")
    p.add_argument("--csv", default=str(DEFAULT_CSV),
                   help=f"Path to CSV file (default: {DEFAULT_CSV})")
    p.add_argument("--db", default=str(DEFAULT_DB),
                   help=f"Path to SQLite database (default: {DEFAULT_DB})")
    p.add_argument("--skip-existing", action="store_true",
                   help="Leave rows that already have an image_description untouched")
    return p.parse_args()


def main() -> None:
    args = parse_args()
    csv_path = Path(args.csv)
    db_path = Path(args.db)

    if not csv_path.exists():
        print(f"ERROR: CSV not found: {csv_path}", file=sys.stderr)
        sys.exit(1)
    if not db_path.exists():
        print(f"ERROR: Database not found: {db_path}", file=sys.stderr)
        sys.exit(1)

    with open(csv_path, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    if not rows:
        print("CSV is empty — nothing to import.")
        return

    conn = sqlite3.connect(str(db_path))
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()

    # Ensure column exists (in case the DB predates the column)
    existing_cols = {r[1] for r in cur.execute("PRAGMA table_info(listings)").fetchall()}
    if "image_description" not in existing_cols:
        cur.execute("ALTER TABLE listings ADD COLUMN image_description TEXT")
        conn.commit()
        print("Added image_description column to listings table.")

    updated = skipped = missing = 0

    for row in rows:
        listing_id = row.get("listing_id", "").strip()
        description = row.get("image_description", "").strip()

        if not listing_id or not description:
            continue

        if args.skip_existing:
            cur.execute(
                "SELECT image_description FROM listings WHERE listing_id = ?",
                (listing_id,),
            )
            existing = cur.fetchone()
            if existing is None:
                missing += 1
                continue
            if existing["image_description"]:
                skipped += 1
                continue

        cur.execute(
            "UPDATE listings SET image_description = ? WHERE listing_id = ?",
            (description, listing_id),
        )
        if cur.rowcount == 0:
            missing += 1
        else:
            updated += 1

    conn.commit()
    conn.close()

    print(f"Done. Processed {len(rows)} rows from {csv_path.name}.")
    print(f"  Updated : {updated}")
    if skipped:
        print(f"  Skipped (already had description): {skipped}")
    if missing:
        print(f"  Not found in DB: {missing}")


if __name__ == "__main__":
    main()
