"""
Import image descriptions from image_descriptions.csv into a local listings.db.

The CSV was generated by export_image_descriptions.py and contains only the
listing_id + image_description columns, so it can be mapped onto any listings.db
that shares the same listing IDs.

Usage:
    uv run python scripts/import_image_descriptions.py
    uv run python scripts/import_image_descriptions.py --csv data/image_descriptions.csv --db data/listings.db
    uv run python scripts/import_image_descriptions.py --skip-existing   # leave already-described rows untouched
"""
from __future__ import annotations

import argparse
import csv
import sqlite3
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Import image descriptions into listings.db")
    p.add_argument("--csv", default=str(ROOT / "data" / "image_descriptions.csv"),
                   help="Path to the CSV file (default: data/image_descriptions.csv)")
    p.add_argument("--db", default=str(ROOT / "data" / "listings.db"),
                   help="Path to the SQLite database (default: data/listings.db)")
    p.add_argument("--skip-existing", action="store_true",
                   help="Do not overwrite rows that already have an image_description")
    return p.parse_args()


def main() -> None:
    args = parse_args()
    csv_path = Path(args.csv)
    db_path = Path(args.db)

    if not csv_path.exists():
        print(f"ERROR: CSV not found: {csv_path}", file=sys.stderr)
        sys.exit(1)
    if not db_path.exists():
        print(f"ERROR: Database not found: {db_path}", file=sys.stderr)
        sys.exit(1)

    with open(csv_path, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    if not rows:
        print("CSV is empty — nothing to import.")
        return

    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()

    updated = skipped = missing = 0

    for row in rows:
        listing_id = row["listing_id"]
        description = row["image_description"]

        if not description:
            continue

        if args.skip_existing:
            cur.execute(
                "SELECT image_description FROM listings WHERE listing_id = ?",
                (listing_id,),
            )
            existing = cur.fetchone()
            if existing is None:
                missing += 1
                continue
            if existing["image_description"]:
                skipped += 1
                continue

        cur.execute(
            "UPDATE listings SET image_description = ? WHERE listing_id = ?",
            (description, listing_id),
        )
        if cur.rowcount == 0:
            missing += 1
        else:
            updated += 1

    conn.commit()
    conn.close()

    total = len(rows)
    print(f"Done. Processed {total} rows from CSV.")
    print(f"  Updated : {updated}")
    if skipped:
        print(f"  Skipped (already had description): {skipped}")
    if missing:
        print(f"  Not found in DB: {missing}")


if __name__ == "__main__":
    main()
